### ISSUE TITLE
Incorrect Header Logo Positioning and Sizing

### ISSUE THREAD

**Issue by ashellwig** [ashellwig/ashhellwig-gatsby#1]
Logo is not correctly sized or positioned in web browsers with a large viewport.

## Possible Solution
Add `margin` or `padding` attributes to the logo class in the `.scss` where it dictates a larger viewport size, above where the same was done for smaller viewport sizes.

## Steps to Reproduce
1. Visit the [published website](https://ashhellwig.netlify.app) or run `gatsby develop` in the project root.
2. Notice that when a google-chrome browser with a standard widescreen aspect ratio is in fullscreen the logo does not
    fit the circle and appears to be too far towards the top. The icon fits well when the window size is reduced.

## Context (Environment)
Using a high-resolution laptop or standard resolution monitor when the google chrome browser window is full size the issue is apparent.

**Comment by JoseLRiano** [comment]
I would like to help to solve this issue.

**Comment by ashellwig** [comment]
Fixed by commit https://github.com/ashellwig/ashhellwig-gatsby/commit/dfbeaf4f3ed40a6146b8cc93defcbbce52c20df0
